INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES(1, 'EUR', 'INR', 80, 0);
INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES(2, 'CAD', 'INR', 55, 0);
INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT) VALUES(3, 'USD', 'INR', 72, 0);